name: Release
on:
  push:
    branches:
      - main

jobs:
  push-images:
    runs-on: nixos-x86_64-linux
    steps:
      - uses: actions/checkout@v3
      - name: Publish images
        run: |
          NIX_ARGS="--extra-experimental-features nix-command --extra-experimental-features flakes"
          NIX="nix ${NIX_ARGS}"
          ${NIX} develop --command skopeo login --username ${REGISTRY_USERNAME} --password ${REGISTRY_PASSWORD} ${REGISTRY_DOMAIN}

          mkdir -p target/
          ${NIX} build .#server-image
          mv result target/swandns.tar.gz
          ${NIX} build .#client-image
          mv result target/swandns-update.tar.gz
          
          VERSION=$(${NIX} develop --command cargo metadata --no-deps --format-version 1 | ${NIX} develop --command jq -r ".packages[0].version")
          ${NIX} develop --command skopeo copy docker-archive:target/swandns.tar.gz docker://${REGISTRY_DOMAIN}/${REGISTRY_IMAGE_SERVER}:${VERSION}
          ${NIX} develop --command skopeo copy docker-archive:target/swandns.tar.gz docker://${REGISTRY_DOMAIN}/${REGISTRY_IMAGE_SERVER}:latest
          ${NIX} develop --command skopeo copy docker-archive:target/swandns-update.tar.gz docker://${REGISTRY_DOMAIN}/${REGISTRY_IMAGE_CLIENT}:${VERSION}
          ${NIX} develop --command skopeo copy docker-archive:target/swandns-update.tar.gz docker://${REGISTRY_DOMAIN}/${REGISTRY_IMAGE_CLIENT}:latest
        env:
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          REGISTRY_DOMAIN: ${{ secrets.REGISTRY_DOMAIN }}
          REGISTRY_IMAGE_SERVER: ${{ secrets.REGISTRY_IMAGE_SERVER }}
          REGISTRY_IMAGE_CLIENT: ${{ secrets.REGISTRY_IMAGE_CLIENT }}
