name: Test
on:
  pull_request:
    branches:
      - main

jobs:
  cargo-test:
    runs-on: nixos-x86_64-linux
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: nix --extra-experimental-features nix-command --extra-experimental-features flakes develop --command cargo test
