name: Test
on:
  pull_request:
    branches:
      - main

jobs:
  cargo-test:
    runs-on: native
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: nix develop --command cargo test
